# bind new keys
unbind r
bind r source-file ~/.tmux.conf; display-message "Configuration reloaded."

# change prefix from 'Ctrl-b' to 'Ctrl-a'
set -g prefix C-a

# active mouse, simplifying resizing
set -g mouse on

# split window with easily to remember keys
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Enable 256 colors
set -g default-terminal "screen-256color"

# Status bar
set -g status-bg colour8
set -g window-status-current-format "#[fg=colour8]#[bg=colour4]#[fg=colour7]#[bg=colour4] #I*#[fg=colour7]#W #[fg=colour4]#[bg=colour8]"
set -g window-status-format "#[fg=colour232]#[bg=colour8] #I#[fg=colour232]#W "

# 1-ref indexing
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# panel
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# list of plugins
set -g @plugin 'tmux-plugins/tpm'

run '~/.tmux/plugins/tpm/tpm'

